In [1]:
import os
import numpy as np
import random
import logging
from itertools import combinations
from typing import Dict, Tuple, List
from pathlib import Path

# Import custom functions from Metabackbone_functions and ER_functions modules
from Metabackbone_functions import (
    load_dna_structure_files, find_longest_strand, find_cross_over_in_longest_strand,
    calculate_left_right_pos, find_valid_point, find_bases_around_point,
    calculate_center_of_mass, calculate_bend_angle, find_bend_angle,
    find_bases_in_sphere, remove_three_strands_in_sphere, export_dna_structures,
    run_all_simulations, stored_removed_strands, remove_one_strand_in_sphere
)

from ipy_oxdna.dna_structure import DNAStructure, DNAStructureStrand, load_dna_structure, DNABase, strand_from_info
from ipy_oxdna.oxdna_simulation import Simulation, SimulationManager


In [2]:
left_indices = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,1356,1357,1358,1359,1360,1361,1362,1363,1364,1365,1366,1367,1368,1369,1370,1371,1372,1373,1374,1375,1376,1377,1378,1379,1380,1381,1382,1383,1384,1385,1386,1387,1388,1389,1390,1391,1392,1393,1394,1395,1396,1397,1398,1399,1400,1401,1402,1403,1404,1405,1406,1407,1408,1409,1410,1411,1412,1413,1414,1415,1416,1417,1418,1419,1420,1421,1422,1423,1424,1425,1426,1427,1428,1429,1430,1431,1432,1433,1434,1435,1436,1437,1438,1439,1440,1441,1442,1443,1444,1445,1446,1447,1448,1449,1450,1451,1452,1453,1454,1455,1456,1457,1458,1459,1460,1461,1462,1463,1464,1465,1466,1467,1468,1469,1470,1471,1472,1473,1474,1475,1476,1477,1478,1479,1480,1481,1482,1483,1484,1485,1486,1487,1488,1489,2161,2162,2163,2164,2165,2166,2167,2168,2169,2170,2171,2172,2173,2174,2175,2176,2188,2195,2196,2197,2198,2199,2200,2201,2202,2203,2204,2205,2206,2207,2208,2209,2210,2211,2212,2213,2214,2215,2216,2217,2218,2219,2220,2221,2222,2223,2224,2225,2226,2227,2228,2229,2230,2231,2232,2233,2234,2235,2236,2237,2238,2239,2240,2241,2242,2243,2244,2245,2246,2247,2248,2249,2250,2251,2252,2253,2254,2255,2256,2257,2258,2259,2260,2261,2262,2263,2264,2265,2266,2267,2268,2269,2270,2271,2272,2273,2274,2275,2276,2277,2278,2279,2280,2281,2282,2283,2284,2285,2286,2287,2288,2289,2290,2291,2292,2293,2294,2295,2296,2297,2298,2299,2300,2301,2302,2303,2304,2305,2306,2307,2308,2309,2310,2311,2312,2313,2314,2315,2316,2317,2318,2319,2320,2321,2322,2323,2324,2325,2326,2327,2328,2329,2330,2331,2332,2333,2334,2335,2336,2337,2338,2339,2340,2341,2342,2343,2344,2345,2346,2347,2348,2349,2350,2351,2352,2353,2354,2355,2356,2357,2358,2359,2360,2361,2362,2363,2364,2365,2366,2367,2368,2369,2370,2371,2372,2373,2374,2375,2376,2377,2378,2379,2380,2381,2713,2748,2749,2750,2751,2752,2753,2754,2755,2756,2757,2758,2759,2760,2761,2762,2763,2764,2765,2766,2767,2768,2769,2770,2771,2772,2773,2774,2775,2776,2777,2778,2779,2780,2781,2782,2783,2784,2785,2786,2787,2788,2789,2790,2791,2792,2793,2794,2795,2796,2797,2798,2799,2800,2801,2802,2803,2804,2805,2806,2807,2808,2809,2810,2811,2812,2813,2814,2815,2816,2817,2977,2978,2979,2980,2981,2986,2987,2988,2989,2990,2991,2992,2993,2994,2995,2996,2997,2998,2999,3000,3001,3002,3003,3004,3005,3006,3007,3008,3009,3010,3011,3012,3013,3014,3015,3016,3017,3018,3019,3020,3021,3022,3023,3024,3025,3026,3027,3028,3029,3030,3031,3032,3033,3034,3035,3036,3037,3038,3039,3040,3041,3042,3043,3044,3045,3046,3047,3048,3049,3050,3051,3052,3053,3054,3055,3056,3057,3058,3059,3060,3061,3062,3063,3064,3065,3066,3067]
right_indices = [20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,862,863,864,865,866,867,868,869,870,871,872,873,874,875,876,877,878,879,880,881,882,883,884,885,886,887,888,889,890,891,892,893,894,895,896,897,898,899,900,901,902,903,904,905,906,907,908,909,910,911,912,913,914,915,916,917,918,919,920,921,922,923,924,925,926,927,928,929,930,931,932,933,934,935,936,937,938,939,940,941,942,943,944,945,946,947,948,949,950,951,952,953,954,955,956,957,958,959,960,961,962,963,964,965,966,967,968,969,970,971,972,973,974,975,1127,1128,1129,1130,1131,1132,1133,1134,1135,1136,1137,1138,1139,1140,1141,1142,1143,1144,1145,1146,1147,1148,1149,1150,1151,1152,1153,1154,1155,1156,1157,1158,1159,1160,1161,1162,1163,1164,1165,1166,1167,1168,1169,1170,1171,1172,1173,1174,1175,1176,1177,1178,1179,1180,1181,1182,1183,1184,1185,1186,1187,1188,1189,1190,1191,1192,1193,1194,1195,1196,1197,1198,1199,1200,1201,1202,1203,1204,1205,1206,1207,1208,1209,1210,1211,1212,1555,1556,1557,1558,1559,1560,1561,1562,1563,1564,1565,1566,1567,1568,1569,1570,1571,1572,1573,1574,1575,1576,1577,1578,1579,1580,1581,1582,1583,1584,1585,1586,1587,1588,1589,1590,1591,1592,1593,1594,1595,1596,1597,1598,1599,1600,1601,1602,1603,1604,1605,1606,1607,1608,1609,1610,1611,1612,1613,1614,1615,1616,1617,1618,1619,1620,1621,1622,1623,1624,1625,1626,1627,1628,1629,1630,1631,1632,1633,1634,1635,1636,1637,1638,1639,1640,1641,1642,1643,1644,1645,1646,1647,1648,1649,1650,1651,1652,1653,1654,1655,1656,1657,1658,1659,1660,1661,1662,1663,1664,1665,1666,1667,1668,1669,1670,1671,1672,1673,1674,1683,1684,1685,1686,1687,1688,1689,1690,1691,1692,1693,1694,1695,1696,1697,1698,1699,1700,1701,1702,1703,1704,1705,1706,1707,1708,1719,1720,1721,2382,2383,2384,2385,2386,2387,2388,2389,2390,2391,2392,2393,2394,2395,2396,2397,2398,2399,2400,2401,2402,2403,2404,2405,2406,2407,2408,2409,2410,2411,2412,2413,2414,2415,2416,2417,2418,2419,2420,2421,2422,2423,2424,2425,2426,2427,2428,2429,2430,2431,2432,2433,2434,2435,2436,2437,2438,2439,2440,2441,2442,2443,2444,2445,2446,2447,2448,2449,2450,2451,2452,2453,2454,2455,2456,2457,2458,2459,2460,2461,2462,2463,2464,2465,2466,2467,2468,2469,2470,2471,2472,2473,2474,2475,2476,2477,2478,2479,2480,2481,2482,2483,2484,2485,2486,2487,2488,2489,2490,2491,2492,2493,2494,2495,2496,2497,2498,2499,2500,2501,2502,2535,2536,2537,2818,2819,2820,2821,2822,2823,2824,2825,2826,2827,2828,2829,2830,2831,2832,2833,2834,2835,2836,2837,2838]

eq_steps = 1e3
prod_steps = 1e3
rel_steps = 1e2
min_distance_threshold = 2.5
min_distance = 7.0
max_distance = 20.0
num_best_structures = 5

num_iterations = 2
sphere_radius = 3.0
desired_angle = 100.0
tolerance = 5.0

input_path = "/home/ava/MetaBackbone_project/Metabackbone-scripts/structure_files/six_helix_oxdna_file/unmodified/1512_bp"

base_path = "/home/ava/MetaBackbone_project/Metabackbone-scripts/structure_files/six_helix_oxdna_file/flexible_joints"

sim_base_path = '/home/ava/MetaBackbone_project/Metabackbone-scripts/Notebook/Simulations_results/Results/optimization_2268_bp'

eq_parameters = {'dt':f'0.003','steps':f'{eq_steps}','print_energy_every': f'1e5', 'interaction_type': 'DNA2',
                 'print_conf_interval':f'1e5', 'fix_diffusion':'false', 'T':f'20C','max_density_multiplier':f'50'}

prod_parameters = {'dt':f'0.003','steps':f'{prod_steps}','print_energy_every': f'1e5', 'interaction_type': 'DNA2',
                   'print_conf_interval':f'1e5', 'fix_diffusion':'false', 'T':f'20C','max_density_multiplier':f'50'}
rel_parameters = {'steps': f'{rel_steps}', 'max_backbone_force': '200', 'max_backbone_force_far': '200'}

In [3]:
# logging.basicConfig(level=logging.INFO, filename='app.log', filemode='w', format='%(asctime)s - %(levelname)s - %(message)s')

In [4]:
def load_dna_structure_files(input_path):
    dat_path = os.path.join(input_path, '1512_bp.dat')
    top_path = os.path.join(input_path, '1512_bp.top')
    dna = load_dna_structure(top_path, dat_path)
    return dna

In [5]:
def find_strands_in_sphere(dna, point, sphere_radius, exclude_strand = None):
    # Find bases within the sphere and map them to their strands
    bases_in_sphere, base_to_strand_mapping = find_bases_in_sphere(dna, point, sphere_radius)
    
    # Identify the strands that have bases within the sphere
    strands_in_sphere = set(base_to_strand_mapping.values())
    longest_strand, longest_strand_index = find_longest_strand(dna)
    
    # Optionally exclude a specific strand by comparing their unique identifiers or indices
    if exclude_strand is not None:
        strands_in_sphere = set(base_to_strand_mapping.values()) - {longest_strand_index}

    return list(strands_in_sphere)


In [6]:
def calculate_left_right_pos(dna, left_indices, right_indices):
    left_pos = []
    right_pos = []
    
    # Debugging output: print the left and right indices
    print("Left indices:", left_indices)
    print("Right indices:", right_indices)
    
    for strand in dna.strands:
        for base in strand:
            # Debugging output: print the UID of each base
            # print(f"Base UID: {base.uid}")  
            if base.uid in left_indices:
                left_pos.append(base.pos)
            elif base.uid in right_indices:
                right_pos.append(base.pos)
                
    # Check and output the positions found for left and right sides
    if left_pos:
        print("Left positions found:", left_pos)
        cms_left_side = np.mean(left_pos, axis=0)
    else:
        raise ValueError("No positions found for left indices.")
    
    if right_pos:
        print("Right positions found:", right_pos)
        cms_right_side = np.mean(right_pos, axis=0)
    else:
        raise ValueError("No positions found for right indices.")
    
    # Calculate and print the midpoint
    midpoint = (cms_left_side + cms_right_side) / 2
    print("Midpoint between the left and right sides:", midpoint)
    
    return cms_left_side, cms_right_side, midpoint


In [7]:
def get_strands_from_bases(dna, base_to_strand_mapping):
    
    longest_strand, longest_strand_index = find_longest_strand(dna)
    strand_indices = set(base_to_strand_mapping.values())- {longest_strand_index}
    return list(strand_indices)

In [8]:
def gather_outside_staples(dna, longest_strand, point, sphere_radius):
    
    longest_strand, longest_strand_index = find_longest_strand(dna)
    bases_in_sphere, base_to_strand_mapping = find_bases_in_sphere(dna, point, sphere_radius)
    
    # Get the strands inside the sphere excluding the longest strand
    strands_in_sphere = set(base_to_strand_mapping.values()) - {longest_strand_index}

    # Gather all other staples outside the sphere and exclude the longest strand
    outside_staples = []
    for strand_index, strand in enumerate(dna.strands):
        if strand_index not in strands_in_sphere and strand != longest_strand:
            outside_staples.append(strand_index)

    return outside_staples

In [9]:
def divide_outside_staples(dna, outside_staples, point):
    left_staples = []
    right_staples = []

    for strand_index in outside_staples:
        strand = dna.strands[strand_index]  # Use square brackets to access the strand
        cms_strand = np.mean([base.pos for base in strand], axis=0)
        if cms_strand[0] < point[0]:  # Adjust based on the axis you consider as left/right
            left_staples.append(strand_index)
        else:
            right_staples.append(strand_index)

    return left_staples, right_staples

In [10]:
dna_structure = load_dna_structure_files(input_path)

In [11]:
strand = dna_structure.strands[23]
print('strand:', strand)

strand: <ipy_oxdna.dna_structure.DNAStructureStrand object at 0x7072c3f7e510>


In [12]:
cms_strand = np.mean([base.pos for base in strand], axis=0)
print('cms_strand:', cms_strand)

cms_strand: [-1.09493105 -0.16945266 36.43973923]


In [13]:
print(cms_strand[0])

-1.094931046079312


In [14]:
strand.bases

array(['A', 'G', 'A', 'T', 'T', 'T', 'T', 'T', 'A', 'A', 'A', 'A', 'A',
       'T', 'G', 'A', 'G', 'A', 'G', 'T', 'C', 'G', 'C', 'C', 'C', 'C',
       'A', 'T', 'G', 'T', 'A', 'T', 'A', 'C', 'T', 'C', 'C', 'C', 'C',
       'G', 'T', 'T'], dtype='<U1')

In [15]:
pos = []
for base in strand:
    print(base.pos)
    pos.append(base.pos)
    
print(pos)

[ 0.42458221 -2.1272223  32.08738708]
[ 0.10870238 -1.96221745 32.47714996]
[-0.24504213 -2.00548005 32.86691284]
[-0.5118497  -2.24173951 33.25667572]
[-0.59759265 -2.58765244 33.6464386 ]
[-0.47202423 -2.92117906 34.03620148]
[-0.17943697 -3.12464738 34.42596436]
[ 0.17693968 -3.12628388 34.81572723]
[ 0.4713771  -2.92550492 35.20549011]
[ 0.60000104 -2.59314561 35.59525299]
[ 0.51743573 -2.24646211 35.98501587]
[ 0.25280258 -2.00776124 36.37477875]
[-0.10052995 -1.96125996 36.76454163]
[-0.41790894 -2.12335801 37.1543045 ]
[-1.78769803 -1.70672429 37.1543045 ]
[-2.12004209 -1.87121022 36.76454163]
[-2.4855969  -1.80893528 36.37477875]
[-2.74472928 -1.54368412 35.98501587]
[-2.79846692 -1.17677891 35.59525299]
[-2.6262753  -0.84836018 35.20549011]
[-2.29393506 -0.68387425 34.81572723]
[-2.04449201  0.69487941 34.81572723]
[-1.74500775  0.88960826 35.20549011]
[-1.60928082  1.22004116 35.59525299]
[-1.68542218  1.56905544 35.98501587]
[-1.94644284  1.81293666 36.37477875]
[-2.29981732

In [16]:
cms_left_side, cms_right_side, midpoint = calculate_left_right_pos(dna_structure, left_indices, right_indices)
print('cms_left_side:', cms_left_side)
print('cms_right_side:', cms_right_side)
print('midpoint:', midpoint)

Left indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 

In [17]:
longest_strand, longest_strand_index = find_longest_strand(dna_structure)

In [18]:
cross_over_bases, max_index_difference, min_distance = find_cross_over_in_longest_strand(longest_strand)

In [19]:
point = find_valid_point (dna_structure, left_indices, right_indices, longest_strand, min_distance_threshold = 2.5)
print('point:', point)

point: [2.33378857e-02 8.94127293e-02 2.43249393e+01]


In [20]:
bases_in_sphere, base_to_strand_mapping = find_bases_in_sphere(dna_structure, point, sphere_radius)


In [21]:
strands_in_sphere = get_strands_from_bases(dna_structure, base_to_strand_mapping)
print('strands in sphere:', strands_in_sphere)

strands in sphere: [35, 45, 19, 20, 21]


In [22]:
outside_staples = gather_outside_staples(dna_structure, longest_strand, point, sphere_radius)
print('outside staples:', outside_staples)

outside staples: [0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 36, 37, 38, 39, 40, 41, 42, 43, 44, 46, 47, 48]


In [23]:
left_staples, right_staples = divide_outside_staples(dna_structure, outside_staples, point)

In [24]:
print(f"Right staples: {right_staples}")
print(f"Left staples: {left_staples}")

Right staples: [1, 24, 27, 38, 39, 40, 41, 42, 43, 44, 46, 47, 48]
Left staples: [0, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 22, 23, 25, 26, 28, 29, 30, 31, 32, 33, 34, 36, 37]
